Major refactor of SetEnvironment.sh.
We now support different program versions.
Needs to be tested on as67 clusters.

diff --git a/LAUNCH/CP2K b/LAUNCH/CP2K
--- a/LAUNCH/CP2K
+++ b/LAUNCH/CP2K
@@ -1,12 +1,17 @@
 #!/bin/bash
 
 input=$1
+version=$2
 nproc=${NSLOTS}
 
 #######LAUNCHING PROGRAM###########
 
 
-source SetEnvironment.sh CP2K
+source SetEnvironment.sh CP2K $version
+if [[ $? != "0" ]];then
+   echo "Error when exporting CP2K parameters in SetEnvironment.sh"
+   exit 1
+fi
 
 DIR=$(pwd)
 SCRDIR=/scratch/$USER/CP2K_$input_${JOB_ID}
@@ -20,7 +25,11 @@ mkdir $SCRDIR
 cp $DIR/* $SCRDIR
 cd $SCRDIR
 
-mpirun -np $nproc $CP2KEXE $input > $DIR/$input.out
+if [[ $proc -gt 1 ]];then
+   $MPIRUN -np $nproc $CP2KEXE_MPI $input > $DIR/$input.out
+else
+   $CP2KEXE $input > $DIR/$input.out
+fi
 
 cp -up * $DIR
 
diff --git a/LAUNCH/MOLPRO b/LAUNCH/MOLPRO
--- a/LAUNCH/MOLPRO
+++ b/LAUNCH/MOLPRO
@@ -2,14 +2,20 @@
 
 #$ -V
 # Molpro 2012 SGE submission script (single- and nulti-processor version)
+version=$2
 source SetEnvironment.sh MOLPRO
+if [[ $? != "0" ]];then
+   echo "Error when exporting MOLPRO parameters in SetEnvironment.sh"
+   exit 1
+fi
 scratch=/scratch/${USER}
 
-export INPFILE=$1
-export LOGFILE=$1.log
-export OUTFILE=$1.out
+INPFILE=$1
+LOGFILE=$1.log
+OUTFILE=$1.out
 
 nproc=${NSLOTS}
+echo "Number of processor is $nproc"
 
 export SCRATCH=${scratch}/M12_$1_${JOB_ID}
 export INTGDIR=${scratch}/M12_$1_${JOB_ID}
@@ -29,7 +35,6 @@ cd ${WORKDIR}
 if [[ "$nproc" -gt 1 ]];then
 
    export PATH=${m12_mpiroot}/bin:$PATH
-   source ${m12_mpiroot}/../libdepends
    export MPIRUN=${MPIDIR}/bin/mpirun
 # -----------------------------------------------------------------
 # Check the hostfile and create scratches and integral directories.
@@ -43,7 +48,7 @@ if [[ "$nproc" -gt 1 ]];then
       ssh ${PE_HOST} "mkdir -p ${SCRATCH}; mkdir -p ${INTGDIR}"
    done
 
-   /usr/bin/time -a -o ${LOGFILE} ${m12_mpiroot}/bin/molpro --launcher "${MPIRUN} %x" <${INPFILE} >> ${LOGFILE}
+   /usr/bin/time -a -o ${LOGFILE} $MOLPROEXE_MPI --launcher "${MPIRUN} %x" <${INPFILE} >> ${LOGFILE}
 
    # Cleaning
    for PE_HOST in $(cat ${PE_HOSTFILE} | cut -f 1 -d " "); do
@@ -56,7 +61,7 @@ else
    mkdir -p ${SCRATCH}
    mkdir -p ${INTGDIR}
 
-   /usr/bin/time -a -o ${LOGFILE} $m12root/bin/molpro <${INPFILE} >>${LOGFILE}
+   /usr/bin/time -a -o ${LOGFILE} $MOLPROEXE <${INPFILE} >>${LOGFILE}
    rm -rf ${SCRATCH}
    rm -rf ${INTGDIR}
 
diff --git a/LAUNCH/ORCA b/LAUNCH/ORCA
--- a/LAUNCH/ORCA
+++ b/LAUNCH/ORCA
@@ -1,9 +1,14 @@
 #!/bin/bash
 
-# Also sets the MPI environment
-source SetEnvironment.sh ORCA
-
 input=$1
+version=$2
+# Also sets the MPI environment
+source SetEnvironment.sh ORCA $version
+if [[ $? != "0" ]];then
+   echo "Error when exporting ORCA parameters in SetEnvironment.sh"
+   exit 1
+fi
+
 KDE=$(pwd)
 
 export PATH=$orcaroot:$PATH
diff --git a/LAUNCH/QCHEM b/LAUNCH/QCHEM
--- a/LAUNCH/QCHEM
+++ b/LAUNCH/QCHEM
@@ -11,11 +11,17 @@ if [ "$#" -lt 1 ] ; then
    exit 1
 fi
 
-source SetEnvironment.sh QCHEM
+version=$3
+parall=$2
+INPUT=$1
 
+source SetEnvironment.sh QCHEM $version
+if [[ $? != "0" ]];then
+   echo "Error when exporting QCHEM parameters in SetEnvironment.sh"
+   exit 1
+fi
 
 export JOBDIR=$(pwd)
-export INPUT=$1
 
 export QCSCRATCH=${JOBDIR}
 export QCLOCALSCR=/scratch/${USER}
@@ -25,9 +31,8 @@ if [[ ${NSLOTS} -eq 1 ]]; then
 
   qchem ${INPUT} ${INPUT}.out &> ${INPUT}.log
 
-elif [[ $2 = "mpi" ]];then
+elif [[ $parall = "mpi" ]];then
 
-  source $mpiset
   source ${qc_mpiroot}/qcenv.sh
   qchem -np ${NSLOTS} ${INPUT} ${INPUT}.out &> ${INPUT}.log
 
diff --git a/LAUNCH/TERA b/LAUNCH/TERA
--- a/LAUNCH/TERA
+++ b/LAUNCH/TERA
@@ -1,7 +1,8 @@
 #!/bin/bash
 if [ -z $1 ];then
 	echo "No input file specified. Exiting..."
-	echo "Call as: $0 input.com [dev]"
+	echo "Call as: $0 input.com [version]"
+        echo "where version is 1.5K or dev."
 	exit 1
 fi
 
@@ -65,10 +66,11 @@ fi
 scrdir=$(grep scrdir $1 | grep -v '#' | head -1 | awk '{print $2}')
 #- All clear, let's go.
 
-if [[ "$2" == "dev" ]];then
-   source SetEnvironment.sh TERAdev
-else
-   source SetEnvironment.sh TERA
+version=$2
+source SetEnvironment.sh TERACHEM $version
+if [[ $? != "0" ]];then
+   echo "Error when exporting TeraChem parameters in SetEnvironment.sh"
+   exit 1
 fi
 
 if [[ -z $scrdir ]];then
