Small fixes.
OCTOPUS: rewrite job.log on each invocation
QCHEM: be more strict about parallel environment
GAUSS: trap qdel and clean scratch files

diff --git a/LAUNCH/OCTOPUS b/LAUNCH/OCTOPUS
--- a/LAUNCH/OCTOPUS
+++ b/LAUNCH/OCTOPUS
@@ -13,7 +13,7 @@ export basedir=$PWD
 export scrdir="/scratch/${USER}"
 export SCRATCH=$scrdir/${JOB_ID}
 
-echo "NODE  ${HOSTNAME}"   >>  $jobfile
+echo "NODE  ${HOSTNAME}"   >  $jobfile
 echo "SCRATCH  ${SCRATCH}"    >>  $jobfile
 echo  $basedir      >>  $jobfile
 echo 'NSLOTS: '${NSLOTS} >>  $jobfile   #NSLOTS
@@ -36,11 +36,16 @@ fi
 cd $SCRATCH
  
 function clean_scratch {
-   echo "Job stopped after qdel ${JOB_ID}">> $jobfile
-   echo "Copying current data back to $basedir/">> $jobfile
    cp -pr * $basedir/.
-   cd ../
-   rm -r $SCRATCH
+   if [[ $? -ne "0" ]];then
+      echo "Error when copying the data from scratch back to the server."
+      echo "I will keep the directory $SCRATCH on node ${HOSTNAME}"
+      exit 1
+   fi
+   if [[ $delscratch -eq "true" ]];then
+      cd ../
+      rm -r $SCRATCH
+   fi
    exit 1
 }
 trap clean_scratch SIGUSR2  #if qdel JOBID then copy current data to basedir
@@ -53,9 +58,5 @@ octopus > $name.out
 fi
 
 echo 'Normal termination of:' ${JOB_ID} >> $jobfile
-cp -pr * $basedir/.
+clean_scratch
 
-if [[ $delscratch -eq "true" ]];then
-  cd ../
-  rm -r $SCRATCH
-fi
diff --git a/LAUNCH/QCHEM b/LAUNCH/QCHEM
--- a/LAUNCH/QCHEM
+++ b/LAUNCH/QCHEM
@@ -8,7 +8,7 @@
 if [ "$#" -lt 1 ] ; then
    echo "Usage: $(/usr/bin/basename $0) <input_file> [par_type] [version] [SAVEWF]"
    echo "par_type is either mpi or openmp"
-   echo "\"SAVEWF\" is the name of the scratch folder woth stored wavefunction"
+   echo "\"SAVEWF\" is the name of the scratch folder with stored wavefunction"
    echo
    exit 1
 fi
@@ -40,10 +40,13 @@ elif [[ $parall = "mpi" ]];then
   source ${qc_mpiroot}/qcenv.sh
   qchem -np ${NSLOTS} ${INPUT} ${INPUT}.out $WF &> ${INPUT}.log
 
-else
+elif [[ $parall = "openmp" ]];then
   source ${qcroot}/qcenv.sh
   qchem -nt ${NSLOTS} ${INPUT} ${INPUT}.out $WF &> ${INPUT}.log
 
+else 
+   echo "ERROR in QCHEM: Incorrent parallel environment! 2nd parameter to this script should be \"mpi\" or \"openmp\""
+   exit 1
 fi
 
 rm -rf TMP core
