Small fixes to launcher.
1. Trap qdel SGE signal in ORCA
2. Support two basis set files in CP2K
3. Support wfn restart in CP2K
4. Print help in fetch.sh

diff --git a/LAUNCH/ORCA b/LAUNCH/ORCA
--- a/LAUNCH/ORCA
+++ b/LAUNCH/ORCA
@@ -17,6 +17,28 @@ input=$(basename $input .com)
 export PATH=$orcaroot:$PATH
 export SCRDIR="/scratch/$USER/ORCA-$input-${JOB_ID}"
 
+function copy_scrdir {
+cp * $KDE
+if [[ $? -ne "0" ]];then
+   echo "Error when copying the data from scratch back to the server."
+   echo "I will keep the directory $SCRDIR on node: $HOSTNAME"
+   exit 1
+fi
+}
+
+function clean_scrdir {
+   echo "Cleaning up temporary files in scratch directory."
+   /bin/rm -rf *.tmp*
+   copy_scrdir
+   cd ../
+   /bin/rm -rf $SCRDIR
+   exit
+}
+
+# The following should trap signal sent by qdel SGE command
+# when submitted with qsub -notify option
+trap clean_scrdir SIGUSR2
+
 echo "NODE  $node" > job.log.${JOB_ID}
 echo "SCRATCH  $SCRDIR" >> job.log.${JOB_ID}
 
@@ -27,15 +49,7 @@ echo "Running ORCA job $1"
 uname -n
 date
 $ORCAEXE $1 &> $KDE/$1.out 
-/bin/rm -rf *.tmp*
-cp * $KDE
-if [[ $? -ne "0" ]];then
-   echo "Error when copying the data from scratch back to the server."
-   echo "I will keep the directory $SCRDIR on node:"
-   uname -a
-   exit 1
-fi
-cd ../
-/bin/rm -rf $SCRDIR
+
+clean_scrdir
 
 
