Tweaks and bug fixes in launchers.

diff --git a/LAUNCH/ORCA b/LAUNCH/ORCA
--- a/LAUNCH/ORCA
+++ b/LAUNCH/ORCA
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+# Also sets the MPI environment
 source SetEnvironment.sh ORCA
 
 input=$1
@@ -8,8 +9,8 @@ KDE=$(pwd)
 export PATH=$PATH:$orcaroot
 
 # DH: I have no idea why this bit was here.
-# Appears to work without it.
-#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/programs/common/intel/compiler/2011.5.220/composerxe-2011.5.220/compiler/lib/intel64/
+# ORCA appears to work without it.
+# export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/programs/common/intel/compiler/2011.5.220/composerxe-2011.5.220/compiler/lib/intel64/
 
 export SCRDIR="/scratch/$USER/orca_$1_${JOB_ID}"
 
@@ -22,6 +23,12 @@ date
 $ORCAEXE $1 &> $KDE/$1.out 
 /bin/rm -rf *.tmp*
 cp * $KDE
+if [[ $? -ne "0" ]];then
+   echo "Error when copying the data from scratch back to the server."
+   echo "I will keep the directory $SCRDIR on node:"
+   uname -a
+   exit 1
+fi
 cd ../
 /bin/rm -rf $SCRDIR
 
